apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::313422618945:role/appstellar-devops-training20220304232117014800000009
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::313422618945:user/amir-pacolli
      username: amir-pacolli
      groups:
        - system:masters
    - userarn: arn:aws:iam::313422618945:user/redon-osmanollaj
      username: redon-osmanollaj
      groups:
        - system:masters
    - userarn: arn:aws:iam::313422618945:user/dea-hoxha
      username: dea-hoxha
      groups:
        - system:masters        
    - userarn: arn:aws:iam::313422618945:user/era-tahiri
      username: era-tahiri
      groups:
        - system:masters  
    - userarn: arn:aws:iam::313422618945:user/fisar-stojkaj
      username: fisar-stojkaj
      groups:
        - system:masters        
    - userarn: arn:aws:iam::313422618945:user/rafet-duriqi
      username: rafet-duriqi
      groups:
        - system:masters           
    - userarn: arn:aws:iam::313422618945:user/besfort-krendali
      username: besfort-krendali
      groups:
        - system:masters           
    - userarn: arn:aws:iam::313422618945:user/armend-hafizademi
      username: armend-hafizademi
      groups:
        - system:masters          
    - userarn: arn:aws:iam::313422618945:user/fjolla-beqiraj
      username: fjolla-beqiraj
      groups:
        - system:masters           
    - userarn: arn:aws:iam::313422618945:user/blin-bicurri
      username: blin-bicurri
      groups:
        - system:masters 
    - userarn: arn:aws:iam::313422618945:user/vigan-bajgora
      username: vigan-bajgora
      groups:
        - system:masters                   