name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
       username: 41632
       password: ${{ secrets.DOCKER_HUB_PASSWORD}}

    - name: Build the Docker image
      working-directory: web-app

      run: 
        docker build . --file Dockerfile --tag 41632/excersice:$(date +%s)
        docker push 41632/excersice:$(date +%s)
